#!/usr/bin/env ruby
$LOAD_PATH.unshift File.dirname(__FILE__) + '/../vendor/plugins/rspec/lib' # For rspec installed as plugin
require 'rubygems'
require 'drb/drb'
require 'rbconfig'
require 'spec'
require 'optparse'

# This is based on Florian Weber's TDDMate
module Spec
  module Runner
    class RailsSpecServer
      
      def run(argv, stderr, stdout)
        $stdout = stdout
        $stderr = stderr
				
        unless ENV['NO_TTY_FAKING']
          # tell rspec it is OK to dump colored output
          # works on OS X, haven't tested anywhere else
          def $stdout.tty?; true; end
          def $stderr.tty?; true; end
        end

        dispatcher = ActionController::Dispatcher.new($stdout)
        dispatcher.run_callbacks :before_dispatch

        if Object.const_defined?(:Fixtures) && Fixtures.respond_to?(:reset_cache)
          Fixtures.reset_cache
        end

        load File.dirname(__FILE__) + '/../spec/spec_helper.rb'

        if in_memory_database?
          load "#{RAILS_ROOT}/db/schema.rb" # use db agnostic schema by default
          ActiveRecord::Migrator.up('db/migrate') # use migrations
        end

        ::Spec::Runner::CommandLine.run(
          ::Spec::Runner::OptionParser.parse(
            argv,
            $stderr,
            $stdout
          )
        )
        
        dispatcher.run_callbacks :after_dispatch, :enumerator => :reverse_each
      end

      def in_memory_database?
        ENV["RAILS_ENV"] == "test" and
        ::ActiveRecord::Base.connection.class.to_s == "ActiveRecord::ConnectionAdapters::SQLite3Adapter" and
        ::Rails::Configuration.new.database_configuration['test']['database'] == ':memory:'
      end
    end
  end
end
ENV["RAILS_ENV"] ||= "test"
puts "Loading Rails #{ENV['RAILS_ENV']} environment"

require File.expand_path(File.dirname(__FILE__) + "/../config/environment")

unless ActiveSupport::Dependencies.mechanism == :load
  puts '==== WARINING =================================================================='
  puts 'ActiveSupport::Dependencies.mechanism is not set to :load, changes to the files are not going to be picked up automaticly.'
  puts "Please set 'config.cache_classes = false' in your config/environments/#{Rails.env}.rb file."
  puts '=' * 80
end

def restart_test_server
  puts "restarting"
  config       = ::Config::CONFIG
  ruby         = File::join(config['bindir'], config['ruby_install_name']) + config['EXEEXT']
  command_line = [ruby, $0, ARGV].flatten.join(' ')
  exec(command_line)
end

def daemonize(pid_file = nil)
  return yield if $DEBUG
  pid = Process.fork{
    Process.setsid
    Dir.chdir(RAILS_ROOT)
    trap("SIGINT"){ exit! 0 }
    trap("SIGTERM"){ exit! 0 }
    trap("SIGHUP"){ restart_test_server }
    File.open("/dev/null"){|f|
      STDERR.reopen f
      STDIN.reopen  f
      STDOUT.reopen f
    }
    yield
  }
  puts "spec_server launched. (PID: %d)" % pid
  File.open(pid_file,"w"){|f| f.puts pid } if pid_file
  exit! 0
end

options = Hash.new
opts = OptionParser.new
opts.on("-d", "--daemon"){|v| options[:daemon] = true }
opts.on("-p", "--pid PIDFILE"){|v| options[:pid] = v }
opts.parse!(ARGV)

puts "Ready"
exec_server = lambda {
  trap("USR2") { restart_test_server } if Signal.list.has_key?("USR2")
  DRb.start_service("druby://127.0.0.1:8989", Spec::Runner::RailsSpecServer.new)
  DRb.thread.join
}

if options[:daemon]
  daemonize(options[:pid], &exec_server)
else
  exec_server.call
end
